{% set name = "verilator" %}
{% set version = "5.006" %}
{% set sha256 = "eb4ca4157ba854bc78c86173c58e8bd13311984e964006803dd45dc289450cfe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  has_prefix_files:
    - share/verilator/include/verilated.mk

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - bison
    - help2man
    - make
    - perl
    - python
    - sed
  host:
    - flex  # need to link against it for target
    - zlib
  run:
    - {{ compiler('cxx') }}  # [osx]
    # there must be a way to derive this from compiler('cxx') but this should work
    - gxx_impl_linux-64  # [linux64]
    - {{ pin_compatible('flex') }}
    - make
    - perl
    - python

test:
  source_files:
    - examples/make_hello_c
  commands:
    - verilator --version
    - cd examples/make_hello_c && make clean default

about:
  home: https://veripool.org/wiki/verilator
  license: GPL-3.0-only OR Artistic-2.0
  license_file:
    - LICENSE
    - Artistic
  summary: The fastest Verilog HDL simulator

  description: |
    Welcome to Verilator, the fastest Verilog HDL simulator.
      • Accepts synthesizable Verilog or SystemVerilog
      • Performs lint code-quality checks
      • Compiles into multithreaded C++, or SystemC
      • Creates XML to front-end your own tools
    Fast
      • Outperforms many commercial simulators
      • Single- and multi-threaded output models
    Widely Used
      • Wide industry and academic deployment
      • Out-of-the-box support from Arm, and RISC-V vendor IP
    Community Driven & Openly Licensed
      • Guided by the CHIPS Alliance and Linux Foundation
      • Open, and free as in both speech and beer
      • More simulation for your verification budget
    Commercial Support Available
      • Commercial support contracts
      • Design support contracts
      • Enhancement contracts
  doc_url: https://www.veripool.org/projects/verilator/wiki/Documentation
  dev_url: https://github.com/verilator/verilator

extra:
  recipe-maintainers:
    - timkpaine
    - timsnyder
